GET http://localhost:3001/api/persons/2

###

GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/6a07ba1d438e4d9b

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Tommy Shelby", 
    "number": "39-44-5323523"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Tommy Shelby", 
    "number": "39-44-5323523"
}